moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fr_leg_controller
    - fl_leg_controller
    - hr_leg_controller
    - hl_leg_controller

  fr_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
    - joint_0 
    - joint_1
    - joint_2

  fl_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
    - joint_3 
    - joint_4
    - joint_5

  hr_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
    - joint_6 
    - joint_7
    - joint_8

  hl_leg_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
    - joint_9 
    - joint_10
    - joint_11