controller_manager:
  ros__parameters:
    update_rate: 10

    fr_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    fl_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hr_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hl_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


fr_leg_controller:
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2

    command_interfaces:
      - position

    state_interface:
      - position
    
    open_loop_control: true
    allow_integration_in_goal_trajectory: true

fl_leg_controller:
  ros__parameters:
    joints:
      - joint_3
      - joint_4
      - joint_5
    
    command_interfaces:
      - position

    state_interface:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectory: true

hr_leg_controller:
  ros__parameters:
    joints:
      - joint_6
      - joint_7
      - joint_8

    command_interfaces:
      - position
      
    state_interface:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectory: true

hl_leg_controller:
  ros__parameters:
    joints:
      - joint_9
      - joint_10
      - joint_11

    command_interfaces:
      - position

    state_interface:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectory: true